merge to master (#4)
* added test circleci config

* line error

* testing CircleCI

* added circleci filtering, updated Gemfile and updated database.yml to use env vars and mysql2 instead of sqlite

* added Dockerfile

* added bundler tasks to development

* updated Gemfile.lock

* added SQL sidecar and run step for testing connectivity

* switched to circleci/ruby:2.4-node-jessie because the baseline ruby image is missing some packages required for CCI testing

* fixed container version for baseline image

* changing the image invalidated the cache. Updated Gemfile to force cache renewal

* had to remove cache block temporarily to test

* updated to ruby 2.4.1 because there is no baseline container in CirclCI for Ruby 2.4.0

* added dependency step

* sudo git add .circleci/config.yml

* lets try this one more time

* one more time

* let's see if this works

* yet another

* I think I got it this time

* added back the restore cache now that permissions have been fixed

* added assets precompile and db migrate test

* updated prod build

* testing env in prod

* lets try this again

* lets try this again

* its always the spaces

* testing tag probe

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,19 +1,108 @@
 version: 2.1
+
+orbs:
+  aws-ecr: circleci/aws-ecr@3.0.0
+
 jobs:
   build_dev:
     docker:
-      - image: ruby:2.4.0
+      - image: circleci/ruby:2.4.1-jessie
+        environment:
+          BUNDLE_WITHOUT: production
+          BUNDLE_JOBS: 3
+          BUNDLE_RETRY: 3
+          BUNDLE_PATH: vendor/bundle
+          MYSQL_USER: root
+          RACK_ENV: development
+
+      - image: tkuchiki/delayed-mysql
+        environment:
+          MYSQL_ROOT_HOST: "%"
+          MYSQL_ALLOW_EMPTY_PASSWORD: yes
+          MYSQL_ROOT_PASSWORD: ''
+          MYSQL_DATABASE: circleci
+
     steps:
+      # Get latest code
       - checkout
+
+      # Baseline image from CCI does not have Rails dependencies installed
+      - run: 
+          name: install_dependencies
+          command: sudo apt-get update && sudo apt-get install -y build-essential libpq-dev nodejs
+
+      # Informational in case of errors later
+      - run:
+          name: which_bundler
+          command: bundle -v
+
+      # If cached gems are found from a previous run, get them and use them. 
+      - restore_cache:
+          keys:
+            - hello-world-{{ checksum "Gemfile.lock" }}
+            - hello-world-
+      
+      # Install Gems from Gemfile.
+      - run:
+          name: bundle_install
+          command: bundle check || bundle install
+
+      # Update Gem cache if needed.
+      - save_cache:
+          key: hello-world-{{ checksum "Gemfile.lock" }}
+          paths:
+            - vendor/bundle
+
+      # Wait for the DB container to come online. This command is a builtin for the container
+      - run: 
+          name: wait_for_db
+          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
+
+      # Create baseline DBs as a sanity check. 
+      - run:
+          name: test_db_connectivity
+          command: bundle exec rake db:create
+
+      # Run assets precompile 
+      - run: 
+          name: assets_precompile
+          command: bundle exec rake assets:precompile
+
+      # Run DB Migrate Rake tasks if present
+      - run:
+          name: db_migrate
+          command: bundle exec rake db:migrate
+
+      # Tests passed! Hello world. 
       - run: echo "hello development"
+
   build_prod:
     docker:
-      - image: ruby:2.4.0
+      - image: circleci/ruby:2.4.1-jessie
+        environment:
+          BUNDLE_WITHOUT: test:development
+          BUNDLE_JOBS: 3
+          BUNDLE_RETRY: 3
+          BUNDLE_PATH: vendor/bundle
+          RACK_ENV: production
+
     steps:
       - checkout
-      - run: echo "hello production"
+      - run:
+          name: test_for_tag
+          command: |
+            echo "$CIRCLE_TAG"
+            if git log -1 --pretty=%B | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
+              continue
+            else
+              echo "Master branch has no tag or has not been tagged properly." 
+              echo "FATAL ERROR. Exiting"
+              exit 1
+            fi
+
 workflows:
   version: 2
+
   development:
     jobs:
       - build_dev:
@@ -21,10 +110,12 @@ workflows:
             branches:
               only:
                 - /^((?!master).)*$/
+
   production:
     jobs:
       - build_prod:
           filters:
             branches:
-              only: /^master$/
+              only: 
+                - master 
 
